# Generated by Django 3.2.5 on 2021-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_participants',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_approved_by',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_date_and_time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_planner',
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(blank=True, default='mercy', max_length=12, null=True),
        ),
    ]
