# Generated by Django 3.2.5 on 2021-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210825_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_planner',
            field=models.CharField(blank=True, default='Samantha', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(blank=True, default='Bool', max_length=12, null=True),
        ),
    ]
