# Generated by Django 3.2.5 on 2021-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_medical_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='documents/%Y/%m/%d'),
        ),
    ]
