# Generated by Django 3.2.5 on 2021-08-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_medical_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
