# Generated by Django 3.2.5 on 2021-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
