# Generated by Django 3.2.5 on 2021-08-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couse_name', models.CharField(blank=True, max_length=10, null=True)),
                ('course_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_schedule', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('couse_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('course_trainer', models.CharField(blank=True, max_length=20, null=True)),
                ('time_in_hours', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
