# Generated by Django 3.2.5 on 2021-08-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='couse_duration',
            new_name='course_duration',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='couse_name',
            new_name='course_name',
        ),
    ]
