# Generated by Django 3.2.5 on 2021-08-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210817_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_schedule',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
